name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## Changes

  $CHANGES

  ## 📦 Installation

  Téléchargez l'exécutable autonome pour Windows x64 :
  - **WSLManager-v$RESOLVED_VERSION-Windows-x64.zip** : Exécutable autonome (pas besoin d'installer .NET)

  ## 🔧 Compilation depuis les sources

  ```bash
  git clone https://github.com/$OWNER/$REPOSITORY.git
  cd $REPOSITORY
  dotnet restore
  dotnet build --configuration Release
  dotnet publish WSLManagerApp/WSLManagerApp.csproj --configuration Release --self-contained true --runtime win-x64
  ```

  ## 📝 Licence

  Ce projet est distribué sous licence **Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)**. 