name: Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore WSLManagerApp/WSLManagerApp.csproj
      
    - name: Build
      run: dotnet build WSLManagerApp/WSLManagerApp.csproj --no-restore --configuration Release
      
    - name: Publish
      run: dotnet publish WSLManagerApp/WSLManagerApp.csproj --no-build --configuration Release --output ./publish --self-contained true --runtime win-x64 --verbosity normal
      
    - name: Create ZIP
      run: |
        $version = $env:GITHUB_REF_NAME -replace 'v', ''
        Compress-Archive -Path "./publish/*" -DestinationPath "WSLManager-v$version-Windows-x64.zip"
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./WSLManager-v${{ github.event.release.tag_name }}-Windows-x64.zip
        asset_name: WSLManager-v${{ github.event.release.tag_name }}-Windows-x64.zip
        asset_content_type: application/zip
        
    - name: Create Checksums
      run: |
        $version = $env:GITHUB_REF_NAME -replace 'v', ''
        Get-FileHash -Path "WSLManager-v$version-Windows-x64.zip" -Algorithm SHA256 | Out-File -FilePath "WSLManager-v$version-Windows-x64.zip.sha256" -Encoding ASCII
        
    - name: Upload Checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./WSLManager-v${{ github.event.release.tag_name }}-Windows-x64.zip.sha256
        asset_name: WSLManager-v${{ github.event.release.tag_name }}-Windows-x64.zip.sha256
        asset_content_type: text/plain 